export interface Tecnicaturas{
    title :string ,
    url : string ,
    description_one : string ,
    url_inscription : string ,
    info_inscription : string ,
    title_obt : string ,
    title_obt_second : string ,
    info_primary : string ,
    info_second : string ,
    title_area?: string ,
    info_area?: string ,
    title_perfil : string ,
    info_perfil : string ,
    info_perfil_1?: string ,
    info_perfil_2?: string ,
    info_perfil_3?: string ,
    info_perfil_req_1?: string ,
    info_perfil_req_2?: string ,
    info_perfil_req_3?: string ,
    info_perfil_req_4?: string ,
    info_perfil_req_5?: string ,
    title_requisitos : string ,
    info_req_1 : string ,
    info_req_2 : string ,
    info_req_3 : string ,
    info_req_4 : string ,
    info_req_5 : string ,
    info_req_6 : string ,
    title_plan_est : string ,
    info_plan_est : string ,
    title_materias : string ,
    title_materias_cuatrimestre_1?: string ,
    info_materias_1 : string ,
    info_materias_2 : string ,
    info_materias_3 : string ,
    info_materias_4 : string ,
    title_materias_cuatrimestre_2?: string ,
    info_materias_5 : string ,
    info_materias_6 : string ,
    info_materias_7 : string,
    info_materias_8 : string ,
    title_general ?: string ,
    info_general_1 ?: string ,
    info_materias_9?: string ,
    title_materias_2 : string ,
    info_materias_seg_1 : string ,
    info_materias_seg_2 : string ,
    info_materias_seg_3 : string ,
    info_materias_seg_4 : string ,
    info_materias_seg_5 : string ,
    info_materias_seg_6 : string ,
    info_materias_seg_7 : string ,
    info_materias_seg_8 : string ,
    info_materias_seg_9 ?: string,
    title_materias_3 : string ,
    info_materias_ter_1 : string ,
    info_materias_ter_2 : string ,
    info_materias_ter_3 : string ,
    info_materias_ter_4 : string ,
    info_materias_ter_5 : string ,
    info_materias_ter_6 ?: string 
}